### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Jane D.",
  "email": "Jane@dow.com",
  "password": "123456"
}


### Register


POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "james@bond.com",
  "password": "123456"
}

### Get User
GET http://localhost:3000/users/21

### Update User

PUT http://localhost:3000/users/update/name/21
Content-Type: application/json

{
  "updatedName": "James Hash 333"
}
### Update User

PUT http://localhost:3000/auth/user/update/26
Content-Type: application/json

{
  "name": "Jane Dow",
  "email": "Jane@dow.com",
  "currentPassword": 123456,
  "password": 123123
}
  