### Filter
GET http://localhost:3000/trips/filter?country=United Kingdom
### Filter complex
GET http://localhost:3000/trips/filter?country=france&city=paris
### Filter complex
GET http://localhost:3000/trips/filter?city=mur mur
### Filter complex
GET http://localhost:3000/trips/filter?rating=3&city=beach
### Filter complex
GET http://localhost:3000/trips/filter

### Get all Trips
GET http://localhost:3000/trips
### Get all user Trips
GET http://localhost:3000/trips/user/id/23


### Get all Trips 404
GET http://localhost:3000/trips4004

### Get single Trip
GET http://localhost:3000/trips/1

### Get trip by country
GET http://localhost:3000/trips/byCountry/2
### Get single Trip
GET http://localhost:3000/trips/deleted

### Create trip
POST http://localhost:3000/trips
Content-Type: application/json

{
    "name": "Trip to Uzbekistan",
    "date": "2004-10-09",
    "country": "Uzbekistan",
    "city": "",
    "rating": 4,
    "description": "Uzbekistan is very beautiful",
    "price": 700,
    "user_id": 2,
    "images_1": "",
    "image_main": "trip.jpg"
}

### Delete single Trip
DELETE  http://localhost:3000/trips/5

### get all countries

GET http://localhost:3000/countries
### get all countries

GET http://localhost:3000/countries/1

### LIKES API

POST  http://localhost:3000/likes

### user LIKES trip

GET   http://localhost:3000/likes/user/26/3
